language: ruby
rvm:
  - 3.0.3
services:
  - postgresql
addons:
  postgresql: "15"
  apt:
    packages:
      - postgresql-15
      - postgresql-client-15
before_install:
  # RUBYGEMS
  - gem update --system
  - gem install bundler
install: bundle install --jobs=3 --retry=3
before_script:
  # POSTGRESQL
  - createuser ranked
  - createdb -O ranked ranked_test
  # SEED
  - bundle exec rails db:migrate
env:
  global:
    - RAILS_TEST_DB_USERNAME=travis
    - PGUSER=travis
    - PGPORT=5433
    - PATH="$HOME/bin:$PATH"
script:
  - rspec spec
