shared:
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>
  username: ranked

development:
  database: ranked_development

test: &test
  host: localhost
  username: <%= ENV.fetch('POSTGRES_USER') { 'tmorgan' } %>
  owner: ranked
  password: <%= ENV.fetch('POSTGRES_PASSWORD') { '' } %>
  database: <%= ENV.fetch('POSTGRES_DB') { 'ranked_test' } %>

cypress: *test

production:
  database: ranked_production
