development:
  host: "localhost:5000"
  https: false
  frontend: "http://localhost:5100"
test:
  host: test.host
  https: false
  frontend: "http://frontend.test.host"
cypress:
  host: "localhost:5000"
  https: false
  frontend: "http://localhost:5100"
production:
  host: ranked.fly.dev
  https: true
  frontend: "https://r4nked.github.io"
