development:
  backend:
    host: "127.0.0.1:5000"
    https: false
  frontend:
    host: "127.0.0.1:5173"
    https: false

test:
  backend:
    host: test.host
    https: false
  frontend:
    host: "frontend.test.host"
    https: false

cypress:
  backend:
    host: "127.0.0.1:5000"
    https: false
  frontend:
    host: "127.0.0.1:4173"
    https: false

production:
  backend:
    host: ranked-app.fly.dev
    https: true
  frontend:
    host: ranked.fly.dev
    https: true
